### ISSUE TITLE
Shooting is slightly off

### ISSUE THREAD

**Issue by agent30632** [Awedtan/LaserTag#10]
**Describe the bug**
When the player shoots, the projectile does not move exactly where you click

**To Reproduce**
1. Shoot somewhere

**Expected behavior**
Should shoot exactly where you click

**Screenshots**
I'll do it later

**Additional context**
Likely not fixable since values are all parsed as ints

**Comment by Awedtan** [comment]
It seems that the slower the bullet, the more it rounds. Setting the projectile speed to a higher number like 20 makes the aiming seem pretty accurate.

**Comment by Awedtan** [comment]
Closing this because raising the projectile speeds basically makes it unnoticeable. We'll just mention it as a bug later.
