### ISSUE TITLE
FOV not working when looking down

### ISSUE THREAD

**Issue by agent30632** [Awedtan/LaserTag#19]
**Describe the bug**
Looking towards the bottom of the screen results in the visible area being cut off at the vertical

**To Reproduce**
1. Look towards the bottom of the screen

**Expected behavior**
FOV should continue past the vertical

**Screenshots**
![image](https://user-images.githubusercontent.com/49417970/71487671-b9b99800-27ea-11ea-8d81-46e7d4632b60.png)

**Additional context**
Likely caused by the way Java parses angles, but not sure

**Comment by Awedtan** [comment]
Half fixed by #28

**Comment by Awedtan** [comment]
Ok nvm not fixed. The fix only works when the fov variable is exactly 45.

**Comment by Awedtan** [comment]
Fixed by 0498c9e
