### ISSUE TITLE
Game cannot be run more than once

### ISSUE THREAD

**Issue by agent30632** [Awedtan/LaserTag#63]
**Describe the bug**
After playing the game, if you exit and try playing again, the game will no longer work

**To Reproduce**
1. Play a game
2. Exit out of the game
3. Attempt to play the game again

**Expected behavior**
The game should run again exactly how it should've before

**Additional context**
Our game is run by using threading, which basically means running the game again would require restructuring some code

**Comment by Awedtan** [comment]
wrong

**Comment by agent30632** [comment]
ok
