### ISSUE TITLE
Replaying speeds up the player and enemies

### ISSUE THREAD

**Issue by Awedtan** [Awedtan/LaserTag#64]
**Describe the bug**
After finishing a game if you choose to exit and play again, the player speed and enemy speeds are drastically higher each time you replay. 

**To Reproduce**
1. Play a game
2. After finishing the game, exit
3. Once in the menu, click play

**Expected behavior**
The player and enemy speeds should be constant. 

**Additional context**
Projectile speeds are unchanged by this bug, so it is not an fps problem

**Comment by agent30632** [comment]
Not caused by multiple mouse listeners, since enemies also speed up. I'll probably still remove the extra movement code though

**Comment by agent30632** [comment]
I was wrong earlier, whoops

**Comment by Awedtan** [comment]
fixed
