### ISSUE TITLE
"Play Again" button does not properly restart game

### ISSUE THREAD

**Issue by agent30632** [Awedtan/LaserTag#65]
**Describe the bug**
"Play Again" button sets you into an empty map. Enemies don't move, you can't move, but you can still rotate and shoot

**To Reproduce**
1. Play a game
2. End the game
3. Click play again

**Expected behavior**
Should work just like clicking "Exit" and "Start" but without going through the menu again

**Additional context**
Reset methods have behaviour seemingly specific to the "exit" stuff, not sure though

**Comment by Awedtan** [comment]
If we can't get the play again button to work we can just take it out. The exit button can be changed to something like "click to continue..." or something

**Comment by agent30632** [comment]
Okay cool, consider the button gone :crab: :crab:
See: 5dcc14985d12822c5f0650bb2ecae90359d0e1c1
